// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATf6cXyXdObxKCVqqKGsXtUm_T8hRSqOE',
    appId: '1:1063805916006:web:0888ae7bba958c5056eea7',
    messagingSenderId: '1063805916006',
    projectId: 'quiz-b5f8c',
    authDomain: 'quiz-b5f8c.firebaseapp.com',
    storageBucket: 'quiz-b5f8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXmjGRiRQ51V8r0lmab_trCKj0PNhEa68',
    appId: '1:1063805916006:android:1000658a69b812a756eea7',
    messagingSenderId: '1063805916006',
    projectId: 'quiz-b5f8c',
    storageBucket: 'quiz-b5f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfCzspzNeuwTIrV1j2thd-QIcng66WEhk',
    appId: '1:1063805916006:ios:dd481ba202d750d856eea7',
    messagingSenderId: '1063805916006',
    projectId: 'quiz-b5f8c',
    storageBucket: 'quiz-b5f8c.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfCzspzNeuwTIrV1j2thd-QIcng66WEhk',
    appId: '1:1063805916006:ios:dd481ba202d750d856eea7',
    messagingSenderId: '1063805916006',
    projectId: 'quiz-b5f8c',
    storageBucket: 'quiz-b5f8c.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATf6cXyXdObxKCVqqKGsXtUm_T8hRSqOE',
    appId: '1:1063805916006:web:e01bfe5ce17f7cf756eea7',
    messagingSenderId: '1063805916006',
    projectId: 'quiz-b5f8c',
    authDomain: 'quiz-b5f8c.firebaseapp.com',
    storageBucket: 'quiz-b5f8c.firebasestorage.app',
  );
}
